"""block table

Revision ID: 9b6610b7aa4a
Revises:
Create Date: 2024-01-23 22:49:16.431289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b6610b7aa4a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "day",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("day", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_day_date"), ["date"], unique=False)

    op.create_table(
        "status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "block",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("task", sa.String(length=256), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["date"],
            ["day.date"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("block", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_block_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_block_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_block_status_id"), ["status_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("block", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_block_status_id"))
        batch_op.drop_index(batch_op.f("ix_block_date"))
        batch_op.drop_index(batch_op.f("ix_block_category_id"))

    op.drop_table("block")
    op.drop_table("status")
    with op.batch_alter_table("day", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_day_date"))

    op.drop_table("day")
    op.drop_table("category")
    # ### end Alembic commands ###
